name: CI

on:
  pull_request:
  push:

jobs:
  ci:
    name: ci-pipeline
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Code Lint
        run: make run-lint

      - name: Dockerfile Lint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
          && apt-get clean \
          && rm -rf /var/lib/apt/lists/* \
          python -m pip install --upgrade pip
          pip install --no-cache-dir --upgrade "poetry==1.1.11"
          poetry config virtualenvs.create false \
            && poetry install $(test "$YOUR_ENV" == production && echo "--no-dev") --no-interaction --no-ansi
      - name: Run Tests
        run: |
          export PYTHONPATH=$PYTHONPATH:/home/runner/work/mypydot/mypydot/src
          PYTHONPATH= poetry run pytest --cov="mypydot" -v tests/ --cov-report=xml

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}