name: CI

on:
  pull_request:
  push:

jobs:
  ci:
    name: ci-pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build image
        run: make build

      - name: Code Lint
        run: make run-lint

      - name: Dockerfile Lint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir --upgrade "poetry==1.1.11"
          poetry config virtualenvs.create false \
            && poetry install $(test "$YOUR_ENV" == production && echo "--no-dev") --no-interaction --no-ansi
      - name: Run Tests
        run: |
          export PYTHONPATH=/home/runner/work/mypydot/mypydot/src
          poetry run pytest --cov="mypydot" -v tests/ --cov-report=xml

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}