name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  ci:
    name: ci-pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Code Lint
        run: make run-lint

      - name: Dockerfile Lint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.11

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false \
            && poetry install $(test "$YOUR_ENV" == production && echo "--no-dev") --no-interaction --no-ansi
      - name: Run Tests
        run: |
          poetry run pytest --cov="src" -v tests/ --cov-report=xml 

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}