name: CI

on:
  pull_request:
  push:

jobs:
  ci:
    name: ci-pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint
        run: make run-lint
      - name: Build image
        run: make build
      - name: Run tests
        run: make run-tests
